name: maintainance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # run "At 00:00 on Sunday"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/franchb/.github-go/tree/main/.github/workflows
jobs:
  vuln:
    uses: franchb/.github-go/.github/workflows/vuln.yml@v0.2.4
  scorecards:
    uses: franchb/.github-go/.github/workflows/scorecards.yml@v0.2.4
  codeql:
    uses: franchb/.github-go/.github/workflows/codeql.yml@v0.2.4
  dependency-review:
    uses: franchb/.github-go/.github/workflows/dependency-review.yml@v0.2.4