name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/franchb/.github-go/tree/main/.github/workflows
jobs:
  build:
    uses: franchb/.github-go/.github/workflows/release.yml@v0.2.4
