name: build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

permissions:
  contents: read

# See https://github.com/franchb/.github-go/tree/main/.github/workflows
jobs:
  build:
    uses: franchb/.github-go/.github/workflows/build.yml@v0.2.5
  test:
    uses: franchb/.github-go/.github/workflows/test.yml@v0.2.5
  lint:
    uses: franchb/.github-go/.github/workflows/lint.yml@v0.2.5
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: franchb/.github-go/.github/workflows/codeql.yml@v0.2.5